site_name: BQ Format
site_url: https://na0fu3y.github.io/bqformat/

theme:
  name: material
  language: ja

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/bqformat

markdown_extensions:
  - codehilite
